on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: create lambda layer
    steps:
      - name: Hello world action step
        run: |
          docker build -t layer .
    container:
      image: layer
      volumes:
        - layers:/layers
    steps:
      - name: copy files from layers
        run: |
          cp /var/lib/docker/volumes/layers/_data .

    