on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: create lambda layer
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          path: staging 
      - name: Hello world action step
        run: |
          docker build -t layer .
          docker run -v layers:/layers --name test1 layer
          docker cp test1:/layers/python_layer.zip .


    