on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: create lambda layer
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Hello world action step
        run: |
          docker build -t layer .
          docker run -v layers:/layers --name test2 layer
          docker cp test2:/layers/python_layer.zip layers


    