on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: create lambda layer
    steps:
      - name: Hello world action step
        run: |
          docker build -t layer .
          docker run -v layers:/layers layer 


    